### ISSUE TITLE
Make run - frontend build fails because Vite and Node type definitions are missing

### ISSUE THREAD

**Issue by rapcmia** [hummingbot/condor#121]
### Describe the bug

After successfully installed condor and run `make run`, the frontend build failed before the application could start. The build runs tsc -b && vite build, but TypeScript stops because it cannot find the vite/client and node type definition files that are referenced in the project TypeScript configuration

```
(base) eddga :: hummingbot/condor/latest ‹main› » vr                                                                                                                                                                                     127 ↵
commit 26a1793145463aac5e73c3a5673ff5d774ba2636
Merge: cc43db2 b691260
Author: Ralph Comia <ralph@hummingbot.org>
Date:   Wed Jun 3 22:40:18 2026 +0800

(base) eddga :: hummingbot/condor/latest ‹main› » make run

> frontend@0.0.0 build
> tsc -b && vite build

error TS2688: Cannot find type definition file for 'vite/client'.
  The file is in the program because:
    Entry point of type library 'vite/client' specified in compilerOptions

  tsconfig.app.json:8:15
    8     "types": ["vite/client"],
                    ~~~~~~~~~~~~~
    File is entry point of type library specified here.

tsconfig.app.json:27:5 - error TS5101: Option 'baseUrl' is deprecated and will stop functioning in TypeScript 7.0. Specify compilerOption '"ignoreDeprecations": "6.0"' to silence this error.
  Visit https://aka.ms/ts6 for migration information.

27     "baseUrl": ".",
       ~~~~~~~~~

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions

  tsconfig.node.json:7:15
    7     "types": ["node"],
                    ~~~~~~
    File is entry point of type library specified here.


Found 3 errors.

make: *** [Makefile:44: build-frontend] Error 1
```

The same build also reports that the baseUrl compiler option is deprecated and will stop working in TypeScript 7.0 unless the project updates the configuration or adds the recommended deprecation ignore setting. The missing type definitions appear to be the immediate blocker, because the install process exits with make: *** [Makefile:44: build-frontend] Error 1.

### Steps to reproduce

1. Check out the Condor repository.
2. Run make run.
3. Wait for the frontend build step to run tsc -b && vite build.
4. Observe that the build fails with missing vite/client and node type definition errors, followed by Makefile:44: build-frontend failure.

### Attach required files

n/a

**Comment by rapcmia** [comment]
Use `make install`
